name: Postman Collection workflow

on:
  push:
    branches:
      - master

  workflow_dispatch:

  schedule:
    - cron: '30 02 * * *'      # 8:00 AM IST
    - cron: '00 14 * * *'      # 7:30 PM IST
    - cron: '00 06 * * 1-5'    # 11:30 AM IST

jobs:
  run-postman-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install Newman and HTML Extra reporter
        run: |
          npm install -g newman
          npm install -g newman-reporter-htmlextra

      - name: Run Postman collection with Newman
        run: |
          newman run "Inwarranty-flow Collection Copy.postman_collection.json" \
            -e "QA.postman_environment.json" \
            -d "testData.csv" \
            -r cli,htmlextra \
            --reporter-htmlextra-export ./newman/index.html

      - name: Upload Newman Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: newman-report
          path: newman/*.html

      - name: Creating github page branch
        if: always()
        uses: peaceiris/actions-gh-pages@v4.0.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: newman/

      - name: Send Email Notification
        if: always()
        uses: dawidd6/action-send-mail@v17
        with:
         server_address: smtp.gmail.com
         server_port: 465
         username: ${{ secrets.EMAIL_USER }}
         password: ${{ secrets.EMAIL_PWD }}
         subject: Phoenix Inwarranty Flow Test Execution Notification
         to: lohakare754@gmail.com
         envelope_from: ${{ secrets.EMAIL_USER }}
         body: |
               Hi,
               The Phoenix Inwarranty flow tests have been executed. The report has been
               published at: https://rslohakare.github.io/Postman-Collection/
      
          
